"use strict";
const DAY=86400000,VALID_LANGS=new Set(["ar","ja"]),VALID_CATEGORIES=new Set(["all","medical","food","aid","important"]);
const safeGet=key=>{try{return localStorage.getItem(key)}catch{return null}},safeSet=(key,value)=>{try{localStorage.setItem(key,value)}catch{}};
const savedLang=safeGet("gh-lang");
const state={lang:VALID_LANGS.has(savedLang)?savedLang:"ar",category:"all",items:[],usingCachedData:false,loading:false};
const $=selector=>document.querySelector(selector),ui={cards:$("#cards"),langBtn:$("#langBtn"),search:$("#searchInput"),searchLabel:$("#searchLabel"),lastSync:$("#lastSync"),offline:$("#offlineNotice"),offlineTitle:$("#offlineNotice strong"),offlineText:$("#offlineNotice span"),refresh:$("#refreshBtn"),hero:$("#heroText"),urgentTitle:$("#urgentTitle"),urgentText:$("#urgentText"),title:$(".topbar h1"),subtitle:$(".subtitle"),categories:$(".categories"),safetyTitle:$(".safety h2"),safetyText:$(".safety p"),footer:$("footer p"),status:$("#statusMessage"),count:$("#resultCount")};
const labels={
 ar:{pageTitle:"مساعدة غزة",title:"مساعدة غزة",subtitle:"معلومات خفيفة • بدون تسجيل • تعمل دون اتصال",search:"ابحث في المعلومات…",searchLabel:"البحث في المعلومات",updated:"آخر تحديث محفوظ على هذا الجهاز",refresh:"تحديث",refreshing:"جارٍ التحديث…",loaded:"تم تحديث المعلومات.",failed:"تعذر الحصول على أحدث المعلومات.",share:"مشاركة",copied:"تم النسخ",copyFailed:"تعذر النسخ. افتح المصدر الرسمي مباشرة.",source:"المصدر الرسمي",verified:"تاريخ التحقق من الرابط",contentDate:"تاريخ المعلومات",empty:"لا توجد نتائج مطابقة.",results:n=>`${n} نتيجة`,hero:"المعلومات المنشورة هنا علنية وقابلة للتحقق. لا يستخدم هذا الموقع لتتبع الأشخاص أو نشر مواقع حساسة.",urgentTitle:"تنبيه مهم",urgentText:"هذا الموقع ليس خدمة طوارئ ولا يقدم نصيحة طبية ولا يضمن توفر الخدمات أو سلامة الطريق. تحقق من أحدث مصدر رسمي والظروف على الأرض قبل اتخاذ قرار أو الانتقال.",sample:"نموذج تجريبي",old:"قد تكون قديمة — تحقق من المصدر",offlineTitle:"وضع عدم الاتصال:",offlineText:"يتم عرض آخر معلومات محفوظة على هذا الجهاز. تحقق من المصدر الرسمي عند عودة الاتصال.",cachedTitle:"تعذر الحصول على أحدث البيانات:",cachedText:"يتم عرض معلومات محفوظة سابقاً. لا تعتمد عليها دون مراجعة المصدر الرسمي.",categoriesLabel:"الفئات",cats:{all:"الكل",medical:"🏥 الرعاية الطبية",food:"💧 الغذاء والماء",aid:"🤝 المساعدة",important:"⚠️ معلومات مهمة"},safetyTitle:"مهم",safetyText:"لا يطلب هذا الموقع اسمك أو رقم هاتفك أو موقعك. قد تتغير الخدمات والطرق بسرعة. تاريخ التحقق يخص الرابط والمصدر فقط، ولا يثبت أن الخدمة متاحة الآن. تحقق من أحدث المعلومات الرسمية والظروف على الأرض.",shareWarning:"تنبيه: موقع مستقل وغير رسمي. تحقق من أحدث مصدر رسمي والظروف على الأرض قبل الاعتماد على هذه المعلومات.",site:"موقع معلومات مساعدة غزة",footer:"موقع مستقل وغير رسمي للاستخدام منخفض البيانات. لا تديره أو تعتمده OCHA أو WHO أو WFP أو UNRWA."},
 ja:{pageTitle:"ガザ支援情報",title:"ガザ支援情報",subtitle:"軽量な情報 • 登録不要 • オフライン対応",search:"情報を検索…",searchLabel:"掲載情報を検索",updated:"この端末に保存された最終更新",refresh:"更新",refreshing:"更新中…",loaded:"情報を更新しました。",failed:"最新情報を取得できませんでした。",share:"共有",copied:"コピーしました",copyFailed:"コピーできませんでした。公式情報源を直接開いてください。",source:"公式情報源",verified:"リンク確認日",contentDate:"情報基準日",empty:"一致する情報はありません。",results:n=>`${n}件`,hero:"掲載情報は公開され、確認可能なものに限定しています。人の追跡や機微な位置情報の公開には使用しません。",urgentTitle:"重要な注意",urgentText:"このサイトは緊急通報・医療相談ではなく、サービスの提供や経路の安全を保証しません。判断や移動の前に、最新の公式情報と現地状況を確認してください。",sample:"デモ情報",old:"古い可能性があります — 出典を確認してください",offlineTitle:"オフラインモード:",offlineText:"この端末に保存された情報を表示しています。通信が戻ったら公式情報源を再確認してください。",cachedTitle:"最新データを取得できませんでした:",cachedText:"以前保存された情報を表示しています。公式情報源を確認せずに依存しないでください。",categoriesLabel:"カテゴリー",cats:{all:"すべて",medical:"🏥 医療",food:"💧 食料・水",aid:"🤝 支援",important:"⚠️ 重要情報"},safetyTitle:"重要",safetyText:"このサイトは氏名・電話番号・現在地の入力を求めません。サービスや経路は急に変わる場合があります。リンク確認日はリンクと情報源の確認日であり、現在の提供状況を示しません。最新の公式情報と現地状況を確認してください。",shareWarning:"注意：独立した非公式サイトです。利用前に最新の公式情報源と現地状況を確認してください。",site:"ガザ支援情報サイト",footer:"低データ通信向けの独立・非公式サイトです。OCHA・WHO・WFP・UNRWAが運営または承認するものではありません。"}
};
const t=()=>labels[state.lang];
function escapeHtml(value=""){return String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function validUrl(value){try{const url=new URL(value);return url.protocol==="https:"?url.href:""}catch{return""}}
function textFor(item,key){return item[`${key}_${state.lang}`]||item[`${key}_ar`]||""}
function fmtDate(value,dateOnly=false){const date=new Date(value);if(!value||!Number.isFinite(date.getTime()))return"—";try{return new Intl.DateTimeFormat(state.lang==="ar"?"ar":"ja-JP",dateOnly?{dateStyle:"medium"}:{dateStyle:"medium",timeStyle:"short"}).format(date)}catch{return String(value)}}
function stale(item){const raw=item.content_date||item.verified_at,time=new Date(raw).getTime();if(!Number.isFinite(time))return true;const max=item.id==="sawa-protection-hotline"||item.id==="ocha-shelter-gaza"?DAY:item.category==="medical"?2*DAY:3*DAY;return Date.now()-time>max}
function allowed(item){return item&&["verified","sample"].includes(item.status)&&typeof item.id==="string"&&typeof item.category==="string"&&textFor(item,"title")&&textFor(item,"body")}
function staticText(){const x=t(),rtl=state.lang==="ar";document.documentElement.lang=state.lang;document.documentElement.dir=rtl?"rtl":"ltr";document.title=x.pageTitle;ui.title.textContent=x.title;ui.subtitle.textContent=x.subtitle;ui.langBtn.textContent=rtl?"日本語":"العربية";ui.langBtn.setAttribute("aria-label",rtl?"تغيير اللغة":"言語を切り替える");ui.search.placeholder=x.search;ui.searchLabel.textContent=x.searchLabel;ui.refresh.textContent=state.loading?x.refreshing:x.refresh;ui.hero.textContent=x.hero;ui.urgentTitle.textContent=x.urgentTitle;ui.urgentText.textContent=x.urgentText;ui.categories.setAttribute("aria-label",x.categoriesLabel);document.querySelectorAll(".cat").forEach(button=>button.textContent=x.cats[button.dataset.category]);ui.safetyTitle.textContent=x.safetyTitle;ui.safetyText.textContent=x.safetyText;ui.footer.textContent=x.footer;notice();lastSync()}
function notice(){const offline=!navigator.onLine,show=offline||state.usingCachedData;ui.offline.hidden=!show;if(show){ui.offlineTitle.textContent=offline?t().offlineTitle:t().cachedTitle;ui.offlineText.textContent=offline?t().offlineText:t().cachedText}}
function render(){staticText();const query=ui.search.value.trim().toLocaleLowerCase(state.lang==="ar"?"ar":"ja");const items=state.items.filter(allowed).filter(item=>(state.category==="all"||item.category===state.category)&&(!query||`${textFor(item,"title")} ${textFor(item,"body")} ${item.source_name||""}`.toLocaleLowerCase().includes(query)));ui.count.textContent=t().results(items.length);ui.cards.setAttribute("aria-busy","false");if(!items.length){ui.cards.innerHTML=`<div class="empty">${escapeHtml(t().empty)}</div>`;return}ui.cards.innerHTML=items.map(item=>{const badge=item.status==="sample"?t().sample:stale(item)?t().old:"",url=validUrl(item.source_url),source=url?`<a class="source-link" href="${escapeHtml(url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(item.source_name||"—")}</a>`:escapeHtml(item.source_name||"—");return`<article class="card"><div class="badge-row">${badge?`<span class="badge ${stale(item)?"stale":""}">${escapeHtml(badge)}</span>`:""}</div><h2>${escapeHtml(textFor(item,"title"))}</h2><p>${escapeHtml(textFor(item,"body"))}</p><div class="card-meta">${escapeHtml(t().verified)}: ${escapeHtml(fmtDate(item.verified_at,true))}</div>${item.content_date?`<div class="card-meta">${escapeHtml(t().contentDate)}: ${escapeHtml(fmtDate(item.content_date,true))}</div>`:""}<div class="source">${escapeHtml(t().source)}: ${source}</div><div class="card-actions"><button class="action" type="button" data-share="${escapeHtml(item.id)}">${escapeHtml(t().share)}</button></div></article>`}).join("")}
async function share(id,button){const item=state.items.find(x=>x.id===id);if(!item)return;const lines=[textFor(item,"title"),textFor(item,"body"),`${t().verified}: ${fmtDate(item.verified_at,true)}`,`${t().source}: ${item.source_name||"—"}`];if(validUrl(item.source_url))lines.push(item.source_url);lines.push("",t().shareWarning,"",`${t().site}: ${location.origin}${location.pathname.replace(/[^/]*$/,"")}`);const text=lines.join("\n");try{if(navigator.share){await navigator.share({title:textFor(item,"title"),text});return}await navigator.clipboard.writeText(text);button.textContent=t().copied;setTimeout(()=>button.textContent=t().share,1500)}catch(error){if(error?.name!=="AbortError")ui.status.textContent=t().copyFailed}}
function lastSync(){const value=safeGet("gh-sync");ui.lastSync.textContent=`${t().updated}: ${value?fmtDate(value):"—"}`}
async function load(){state.loading=true;ui.refresh.disabled=true;ui.cards.setAttribute("aria-busy","true");ui.status.textContent=t().refreshing;staticText();try{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000),response=await fetch("./data.json",{cache:"no-store",signal:controller.signal});clearTimeout(timer);if(!response.ok)throw new Error(`HTTP ${response.status}`);const data=await response.json();if(!Array.isArray(data))throw new Error("Invalid data");state.items=data;state.usingCachedData=false;const now=new Date().toISOString();safeSet("gh-data",JSON.stringify(data));safeSet("gh-sync",now);ui.status.textContent=t().loaded}catch(error){try{const cached=JSON.parse(safeGet("gh-data")||"[]");state.items=Array.isArray(cached)?cached:[]}catch{state.items=[]}state.usingCachedData=true;ui.status.textContent=t().failed;console.warn("Data load failed",error)}finally{state.loading=false;ui.refresh.disabled=false;render()}}
document.addEventListener("click",event=>{const shareButton=event.target.closest("[data-share]");if(shareButton)share(shareButton.dataset.share,shareButton);const cat=event.target.closest(".cat");if(cat&&VALID_CATEGORIES.has(cat.dataset.category)){state.category=cat.dataset.category;document.querySelectorAll(".cat").forEach(button=>{const active=button===cat;button.classList.toggle("active",active);button.setAttribute("aria-pressed",String(active))});render()}});
ui.langBtn.addEventListener("click",()=>{state.lang=state.lang==="ar"?"ja":"ar";safeSet("gh-lang",state.lang);render()});ui.search.addEventListener("input",render);ui.refresh.addEventListener("click",load);window.addEventListener("online",load);window.addEventListener("offline",notice);if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(console.warn));staticText();load();
